sudo: required
services:
  - docker

before_install:
  - docker build -t zhadyrassyn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run zhadyrassyn/react-test npm run test -- --coverage

after_success:
  - docker build -t zhadyrassyn/multi-client ./client
  - docker build -t zhadyrassyn/multi-nginx ./nginx
  - docker build -t zhadyrassyn/multi-server ./server
  - docker build -t zhadyrassyn/multi-worker ./worker
  # Log in to the Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push to Docker hub
  - docker push zhadyrassyn/multi-client
  - docker push zhadyrassyn/multi-nginx
  - docker push zhadyrassyn/multi-server
  - docker push zhadyrassyn/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multii-docker
  env: MultiiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-478387899082
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
